### PR TITLE
Keystone v3

### PR DESCRIPTION
**Pull request by reimannf**
Hi Mark. I tried to get more OS_ like variables into getput to get support for keystone v3 specifics like OS_PROJECT_DOMAIN_NAME working. Furthermore I moved to creds_file parsing in the parse_creds method, to have ENV variables and creds file settings in a common place.

### CODE REVIEW

**Comment by majewsky** [comment]
@markseger I resolved the merge conflicts and cleaned the diff a bit. Would be nice to have this merged if you like it.

**Comment by markseger** [comment]
I tried to figure out what you changed and all I see is changing to text
files.  I also admit to not doing a lot with git.  What exactly did you
change for keystone?  I'm certainly happy to make them.  This is also
further complicated by the fact that I've made a number of changes I was
getting ready to upload and now I'm not sure what to do.
-mark

**Comment by majewsky** [comment]
There are a lot of changes in `getput`, the main Python script, if you look at the overall diff of the branch, not just my commits.

The changes are mostly related to adding support for the Keystone v3 API. v1 and v2 are both deprecated, and don't work in our team's OpenStack deployments because we use multiple Keystone domains.

If you want to merge your own work, then by all means, do so. I can resolve the merge conflicts with our branch after that.

**Comment by markseger** [comment]
I finally got around to pushing out a new version.  I had also talked to a
couple of internal folks who are also swift core developers and are
familiar with getput.  They said that getput currently does support
keystone v3 but not domains which require recognizing OS_USER_DIOMAIN_NAME,
_ID and OS_PROJECT_DOMAIN_NAME and _ID.  What did confuse me is I didn't
see any references to 'domain' in your patch listing.

Anyhow if you do generate a new diff against the latest version I'm hoping
your changes will be clearer

-mark

**Comment by reimannf** [comment]
Hi @markseger. I introduced exactly the mentioned variables here: https://github.com/markseger/getput/pull/2/files#diff-1976fc593852dbc7e3665c1ceee90b0e and some other. But let us resolve the merge conflicts first.

**Comment by reimannf** [comment]
Conflicts resolved

**Comment by markseger** [comment]
looking at this patch and it looks like you cleaned up somethign that
always bothered me.  when I first wrote getput there was only V1 auth and
it used the ST_ varibles.  Then I added the OS_ style ones but not all.  It
looks like you've gotten rid of my passing tenant_id and tenant_name to
connect() and instead putting them and the domain stuff onto osvars and
just passing it.  nice.

it also looks like you got rid of my code that tries to parse a credentials
file that contains a bunch of exports.  I never did like that  ;)  but it
may also break gpsuite/gpmulti which don't deal with env vars but only pass
the name of the credentials file.  however, I'm thinking with some playing
around perhaps I can just source it when calling getput from gpmulti.  I'm
sure I can figure it out.

in any event I can wait for you to resolve and conflicts that may have come
up.

so I assume since you did go to the trouble of patching this you are a
getput user.  can I assume you like it?  have you played with gpsum and/or
gpwhere at all?  both very helpful. and of course there's gpsuite for
running on multiple clients in parallel. ;)

-mark

**Comment by reimannf** [comment]
The credentials file should still work https://github.com/reimannf/getput/blob/c8b26e6b6c6be14909de96536d2b5b5144874dc6/getput#L423. I was aware that other parts are relying on that. But I tried to unify processing ENV variables and the credentials file into one place because of my lazyness. `parse_creds` takes now an optional argument - the credential file and super seeds the environment https://github.com/reimannf/getput/blob/c8b26e6b6c6be14909de96536d2b5b5144874dc6/getput#L181. 

Yes we are using getput and for me it was very easy to get the basic information I need to know about our swift installations: throughput and latency. Benchmark suites like rally are not what I am looking for. But we are running with keystone v3 and a lot of domains.
I am also aware of the gpsuite, but we did not use that heavily so far.

**Comment by markseger** [comment]
yes, I already tried gpsuite with your version of getput and it works fine.
  my problem now is trying to figure out how to merge it!  I saw a merge
button in github and clicked it but I dont' think it worked.  do you know
the steps I need to go through?

do you ever use latexc?  I can't live without it when trying to find slow
transactions.  then take the output and send through gpwhere and you can
see a very compact summary of how much time spent on the proxies,
containers and object servers.

-mark

**Comment by reimannf** [comment]
Hhmm. I see only that you closed the pull request and that there unmerged commits. I think you can open it again and than hitting the merge button should do it - Merge and Confirm Merge. Can you try to open that guy https://github.com/markseger/getput/pull/2 again? 

I know the latexc option, but gpwhere is not helpful in our setup, as we have the storage logs separated by server type account.log, container.log, ... So effectively we ship our logs to elastic search and throw kibana over it.

**Comment by markseger** [comment]
I think that did it!  As for latexc, if you run getput like this:
getput ... --latexc .5 and save all the exceptions to a file OR
getput ... --latexc .5 --exclog xxx it will write the exception to file xxx

now, just run gpwhere -sswift -tfilename -V

where swift is a file containing the addresses of all your servers and you'll see output like this:

without -V, everything prints on a single line which makes it really easy to see differences b/w nodes, but not very good for email.  -V breaks the output into 3 sections, for the proxy, container and object servers.

In this case I did 10 puts with latexc set to 0 so I'd get 10 exception which display like this, only showing the first 2.  You can now easily see the time spent talking to the proxy, container and object server as well as which data disk the object server was talking to.  Makes it real easy to spot who may be a problem.  In the first case 2 object servers only took about 6 msec to do the put but the 3rd took over 26 msec which is why the overall time in the proxy was 32 msec.

./gpwhere -sswift -txxx -V

tx6cd481d5ea7a4783832b6-0058472932 21:10:06  1  0.035
  p/swpac-m1 0.0325
  c/swpac-m1 0.0005  c/swpac-m2 0.0005  c/swpac-m3 0.0005
  o/swobj0001-mgmt:disk2   0.0066  o/swobj0002-mgmt:disk2   0.0267  o/swobj0003-mgmt:disk3   0.0060
tx6ef1357d58bf48f78354e-0058472932 21:10:06  1  0.039
  p/swpac-m1 0.0367
  c/swpac-m1 0.0005  c/swpac-m2 0.0005  c/swpac-m3 0.0006
  o/swobj0001-mgmt:disk2   0.0068  o/swobj0002-mgmt:disk2   0.0309  o/swobj0003-mgmt:disk3   0.0064

-mark

**Comment by reimannf** [comment]
Thanks for merging

regarding the gpwhere - I understand the usecase and the analyzing help. But if I interpret your code correct https://github.com/markseger/getput/blob/master/gpwhere#L160 you expect the logs in `/var/log/swift/swift.log` - we have separated them per server type `/var/log/swift/proxy.log`, `/var/log/swift/object.log`, `/var/log/swift/container.log`and so on.

**Comment by markseger** [comment]
re locations, gottcha.  maybe you could send me your private email address
so we don't have to clog up github
maybe v2 of gpwhere could have a conf file to tell it where to look but
that would also add a new level of complexity at least for the pdsh use case

**Pull request merged**
